name: api-build

on:
  push:
    paths:
      - ".github/workflows/api-build.yml"
      - "api/**"
  pull_request:
    paths:
      - "api/**"
  workflow_dispatch: # manual

jobs:
  build:
    name: build-it
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: net6
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: 9.0.x
      #     dotnet-quality: preview
      - run: |
          pwd
          dotnet --version
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        #working-directory: net6

# cdr # avoid path issues
# act --workflows .github/workflows/api-build.yml --reuse
