name: cd-created-deployment

on:
  # deployment_status:   # 3rd party deployment trigger (webhook)
  deployment:
    # docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#deployment
    # no type fitler (on created only, so not gonna smoke test unless gonna wait for deployment job to finish)
    #   FYI deployment is created BEFORE approval is made, so just keep that in mind too... so you could use this to alert someone or otherwise trigger initial actions
    # payload GITHUB_SHA and GITHUB_REF

jobs:
  created:
    runs-on: ubuntu-latest
    steps:
      - name: Log the event payload
        run: echo "${{ toJson(github.event.deployment) }}"
        # FYI:
        #   github.event.deployment =>
        #     ref=master, sha=f38a...,
        #     environment: production, original_environment=production, production_environment: false,
        #     id (deployment): 1111..., repository_url: https://api.github.com/repos/g0t4/tmp-prep-course-gh-actions
        #     (deployment) statuses_url: https://api.github.com/repos/g0t4/tmp-prep-course-gh-actions/deployments/1523171313/statuses
        #     task: deploy, transient_environment: false
