on:
  # deployment_status:   # 3rd party deployment trigger (webhook)
  deployment:
    # docs: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#deployment
    # no type fitler (on created only, so not gonna smoke test unless gonna wait for deployment job to finish)
    # payload GITHUB_SHA and GITHUB_REF

jobs:
  created:
    runs-on: ubuntu-latest
    steps:
      - name: Log the event payload
        run: echo "${{ toJson(github.event.deployment) }}"
