name: cd-deploy2-1-build

on:
  push:
    paths:
      - ".github/workflows/cd-deploy.yml"
      - "api/**"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # https://github.com/actions/checkout/blob/v4/action.yml
          # fetch-tags: true # don't need to fetch commits for other tags, just need commits of current branch
          fetch-depth: 0 # all commits, so we can generate version off of tags/commit sha... could be more efficient to use smth like: parse release-X branch via ref + commit sha
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx ls
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - run: ./build-push.sh # can reuse local build scripts for CI/CD
        working-directory: api
