name: cd-deploy dotnet

on:
  push:
    paths:
      - ".github/workflows/cd-deploy.yml"
      - "api/**"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx ls
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - run: docker compose build --pull
      - run: docker compose push
      # PRN try not just building latest? and instead use a tag w/ a version?
