name: cd deploy2 on create deploy

on:
  deployment: # trigger when a deployment is created

jobs:
  alerts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "sending slack alert that deploy created..."
