name: cd-smoke

on:
  workflow_run:
    workflows: ["cd-deploy"] # careful w/o name, IIRC has to be the "name" not the file name w/o prefix... # TODO double check this
    types:
      - completed # both success,failure # use condition in steps => if: ${{ github.event.workflow_run.conclusion == 'success' }}
  workflow_dispatch: # manual (don't have to deploy to test)
    inputs:
      head_sha:
        description: "The commit sha to test, manually provided"
        required: false
        # default, empty is fine

jobs:
  smokeit:
    runs-on: ubuntu-latest
    steps:
      - run: env # TODO remove this later
      - name: Log the event payload
        run: echo "${{ toJson(github.event.workflow_run) }}"
        # docs workflow_run payload => https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run
        #
        # FYI:
        #   github.event.workflow_run =>
        #     id: 1111..., run_number: 1, run_id: 1111..., run_url:
        #     head_sha => commit sha for the workflow run (deploy job) => use this to get the version of the deployed app
        #        git describe --tags head_sha
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # git describe --tags # in smoke-test.sh
      - run: curl -fsSL "http://gh-actions-web-api.azurewebsites.net/" # PRN pass url arg?s

      # if workflow_run => use head_sha, if manual (workflow_dispatch) => use inputs.head_sha... AWESOME
      - run: ./smoke-test.sh "${{ github.event.workflow_run.head_sha || inputs.head_sha }}"
        working-directory: api

      # https://github.com/marketplace/actions/url-health-check
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v4
        with:
          # https://github.com/Jtalk/url-health-check-action/blob/master/action.yml
          url: "http://gh-actions-web-api.azurewebsites.net/version"
          max-attempts: 2
          retry-delay: 5s
          # follow-redirect: true
