name: deployer

on:
  push:
    paths:
      - ".github/workflows/deployer.yml"
  workflow_dispatch: # manual

jobs:
  # predeploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo building
  #     - run: echo "BUTLER_MODEL= ${{ vars.BUTLER_MODEL}}"
  #     # - run: echo "DEPLOY_KEY= ${{ secrets.DEPLOY_KEY }}" # warning if try to include this

  testing:
    # needs: predeploy
    runs-on: ubuntu-latest
    # environment: staging
    container:
      image: mysql:5.7 # TODO client only image?
    steps:
      - run: mysql --version

  # deploy:
  #   needs: predeploy
  #   runs-on: ubuntu-latest
  #   environment: production

  #   steps:
  #     - run: echo "BUTLER_MODEL= ${{ vars.BUTLER_MODEL}}"
  #     - run: echo "DEPLOY_KEY= ${{ secrets.DEPLOY_KEY }}" # i.e. defined only in prod/stating
  #     - run: echo "deploying"
  #     - run: echo "deployed"
