name: deployer

on:
  push:
    paths:
      - ".github/workflows/deployer.yml"
  workflow_dispatch: # manual

jobs:
  predeploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo building
      - run: echo "${{ vars.BUTLER_MODEL}}"
      # - run: echo "${{ secrets.DEPLOY_KEY }}" # warning if try to include this

  deploy:
    needs: predeploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - run: echo "${{ vars.BUTLER_MODEL}}"
      - run: echo "${{ secrets.DEPLOY_KEY }}"
      - run: echo "deploying"
      - run: echo "deployed"
