name: deployer

on:
  push:
    paths:
      - ".github/workflows/deployer.yml"
  workflow_dispatch: # manual

jobs:
  # predeploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo building
  #     - run: echo "BUTLER_MODEL= ${{ vars.BUTLER_MODEL}}"
  #     # - run: echo "DEPLOY_KEY= ${{ secrets.DEPLOY_KEY }}" # warning if try to include this

  testing:
    # needs: predeploy
    # environment: staging
    runs-on: ubuntu-latest
    container:
      image: mysql:5.7 # TODO client only image?
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - run: mysql --version
      - run: mysql -h mysql -u root -proot -e "SHOW DATABASES;"
      - run: echo "${{ toJson(job.services)}}"
      - run: echo "${{ toJson(job.container)}}"

  # deploy:
  #   needs: predeploy
  #   runs-on: ubuntu-latest
  #   environment: production

  # deploy:
  #   needs: predeploy
  #   runs-on: ubuntu-latest
  #   environment: production

  #   steps:
  #     - run: echo "BUTLER_MODEL= ${{ vars.BUTLER_MODEL}}"
  #     - run: echo "DEPLOY_KEY= ${{ secrets.DEPLOY_KEY }}" # i.e. defined only in prod/stating
  #     - run: echo "deploying"
  #     - run: echo "deployed"
