name: gh-api

on:
  push:
    paths:
      - ".github/workflows/gh-api.yml"
  workflow_dispatch: # manual

jobs:
  gh_cli:
    runs-on: ubuntu-24.04
    steps:
      - run: gh --version
      - run: gh auth status
      - run: gh repo list
      - uses: actions/checkout@v4
      - run: gh workflow list # --repo g0t4/tmp-prep-course-gh-actions
      - run: gh run list # --repo g0t4/tmp-prep-course-gh-actions
      # - run: gh api /repos/g0t4/tmp-prep-course-gh-actions/actions/workflows
    env:
      GITHUB_TOKEN: ${{ github.token }}
