# quick test of git commmand and checkout:
name: git test

on:
  push:
    paths:
      - ".github/workflows/git-test.yml"
  workflow_dispatch: # manual

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      #  with: # https://github.com/actions/checkout/blob/v4/action.yml
      #    fetch-tags: true
      - run: which git
      - run: git --version
      - run: git describe --tags
      - run: env
