name: inspect runner image

on:
  push:
    paths:
      - ".github/workflows/inspect-runner-image.yml"
      - "upper/**"
  workflow_dispatch: # manual

# FYI go guide: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ubuntu-24.04
    steps:
      - run: cat /etc/os-release
      - run: which -a go
      - run: go version
      - run: go env
