name: inspect runner image

on:
  push:
    paths:
      - ".github/workflows/inspect-runner-image.yml"
      - "upper/**"
  workflow_dispatch: # manual

# FYI go guide: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04] # , ubuntu-latest] confirmed ubuntu-latest points to 22.04
    runs-on: ${{ matrix.os }}
    steps:
      - run: env
      # instead of trusting the runner image readmes, you can validate what is available in a given runner
      - name: show path dir contents w/ ls
        run: |
          IFS=':' read -r -a dirs <<< "$PATH"

          for dir in "${dirs[@]}"; do
            echo && echo "Listing contents of: $dir"
            ls -al "$dir" || true
          done
      - name: hosted tool cache
        run: |
          echo && echo tree -L 3 /opt/hostedtoolcache
          tree -L 2 /opt/hostedtoolcache || true
      - run: cat /etc/os-release
      - run: which -a go
      - run: go version
      - run: go env
