name: live-upper-build

on:
  push:
    paths:
      - ".github/workflows/live-upper-build.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: go version
      - run: go build
        working-directory: ./upper