name: mod issues

on:
  push:
    paths:
      - ".github/workflows/mod-issues.yml"
  workflow_dispatch: # manual

env:
  FOO: bar

jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo "${{ toJson(env) }}" # what is set (thus far) in the job => not same as env command (what runner sees), autocomplete based on workflow file (i.e. env.FOO completes here)
      - run: |
          env # point out masked GH_TOKEN
          gh auth status
          # gh api user
          gh repo list # only lists this single repo
        env:
          # FYI gh CLI => env vars docs: https://cli.github.com/manual/gh_help_environment
          GH_TOKEN: ${{ github.token }}
      # plenty in this example already, jump to open ai next
      # - uses: actions/checkout@v4
      #
      # env ideas:
      # - run: echo "::set-env name=HELLO::world" # disabled https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
      - run: echo "HELLO=world" >> $GITHUB_ENV
      - run: env
      - run: echo "${{ toJson(env) }}"
