name: mod issues

on:
  push:
    paths:
      - ".github/workflows/mod-issues.yml"
  workflow_dispatch: # manual

jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo "${{ toJson(env) }}" # not same as env command (what runner sees)
      - run: |
          env # point out masked GH_TOKEN
          gh auth status
          # gh api user
          gh repo list # only lists this single repo
        env:
          # FYI gh CLI => env vars docs: https://cli.github.com/manual/gh_help_environment
          GH_TOKEN: ${{ github.token }}
      - uses: actions/checkout@v4
      # plenty, jump to open ai next
