name: prep go pkg2

on:
  push:
    paths:
      - ".github/workflows/prep-go-pkg2.yml"
      - "upper/**"
  workflow_dispatch: # manual

# FYI go guide: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

jobs:
  # rearrange to checkout before setup-go so we can use go-version-file: 'upper/go.mod'
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "upper/go.mod"
          cache-dependency-path: "upper/go.sum"
      - run: go version

      - run: go mod download
        working-directory: upper
      - run: |
          ls # before build
          go build
          go test
          ls # after build => upper! (executable)
          echo
          ./upper foo the bar
        working-directory: upper

      - uses: actions/upload-artifact@v4
        with:
          name: upper
          path: upper/upper
