name: scheduled-workflow

on:
  schedule:
    # hourly: 0 * * * *
    # daily: 0 0 * * *
    # every 10 minutes: */10 * * * *
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
