name: upper image build

on:
  push:
    paths:
      - ".github/workflows/upper-image.yml"
      - "upper"
  workflow_dispatch: # manual

permissions:
  packages: write
  contents: read

jobs:
  image:
    name: image-pkg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker image build -t upper .
        working-directory: ./upper
      - name: test it
        run: docker container run upper foo the bar
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag upper ghcr.io/${{ github.repository_owner }}/upper:${{ github.ref_name }}
      # mention can tag with ${{ github.ref_name }} and filter on tags only (like we did with Releases)
      - run: docker push ghcr.io/${{ github.repository_owner }}/upper:${{ github.ref_name }}
