name: upper image build

on:
  push:
    paths:
      - ".github/workflows/upper-image.yml"
      - "upper"
  workflow_dispatch: # manual

permissions:
  packages: write

jobs:
  build:
    name: build-it
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: upper
    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker image build -t upper .
      - name: test it
        run: docker container run upper foo the bar
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag upper ghcr.io/${{ github.repository_owner }}/upper:latest
      - run: docker push ghcr.io/${{ github.repository_owner }}/upper:latest
      # PRN also tag version? if ref is tags/v*
